name: Idle-Master-Extended

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    
    - name: Lets Download Idle Master Extended
      run: Invoke-WebRequest https://github.com/JonasNilson/idle_master_extended/releases/download/v1.7/idle_master_extended_v1.7.zip -OutFile idle.zip
      
    - name: Unzipping Idle master Extended
      run: Expand-Archive idle.zip
    
    - name: Moving IDLE to Desktop and checking it
      run: |
       Move-Item D:\a\Idle-Master-Extended\Idle-Master-Extended\idle ~\Desktop\
       cd ~\Desktop\
       dir
       
    - name: Download Steam
      run: |
       Invoke-WebRequest https://cdn.cloudflare.steamstatic.com/client/installer/SteamSetup.exe -OutFile SteamSetup.exe
       dir
       
    - name: Installing Steam
      run: start-process SteamSetup.exe /S
     
    - name: Starting Idle Master
      run: |
       dir
       start-process ~\Desktop\idle\idle_master_extended_v1.7\IdleMasterExtended.exe
     
    - name: Opening Steam
      run: |
       start-process 'C:\Program Files (x86)\Steam\Steam.exe'
       dir
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 3389 
