name: CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip

    - name: Downloading Idle Master Extended
      run: Invoke-WebRequest https://github.com/JonasNilson/idle_master_extended/releases/download/v1.7/idle_master_extended_v1.7.zip -OutFile idle.zip
      
    - name: Checking DIR
      run: dir
    
